### ISSUE TITLE
Ravendb azure

### ISSUE THREAD

**Issue by rvwv** [anton-iermolenko/Azure-IIS-Hosted-RavenDb#1]
thanks for the solution

**Comment by anton-iermolenko** [comment]
You have to set your Azure storage connection string in ServiceConfiguration.Cloud replacing "UseDevelopmentStorage=true"

Thanks,
Anton

12 січ. 2012 о 11:22 "herve bansay" reply@reply.github.com написав(ла):

**Comment by anton-iermolenko** [comment]
Glad it was useful
