### ISSUE TITLE
Error when create new database on azure

### ISSUE THREAD

**Issue by rvwv** [anton-iermolenko/Azure-IIS-Hosted-RavenDb#3]
I get this error when i open new database and read document from new database,
any suggestions ?

my code :

DocStore.DatabaseCommands.EnsureDatabaseExists(databaseName);
var session = DocStore.OpenSession(databaseName);
var settings = session.Load<Settings>("Settings/1");

System.InvalidOperationException: {
  "Url": "/databases/stef.crmlet.com/docs/Settings/1",
  "Error": "System.InvalidOperationException: Could not open transactional storage: B:\Tenants\stef.crmlet.com\Data ---> Microsoft.Isam.Esent.Interop.EsentLogDiskFullException: Log disk full\r\n   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err)\r\n   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator) in c:\Builds\raven\Raven.Storage.Esent\TransactionalStorage.cs:line 207\r\n   --- End of inner exception stack trace ---\r\n   at Raven.Storage.Esent.TransactionalStorage.Initialize(IUuidGenerator uuidGenerator) in c:\Builds\raven\Raven.Storage.Esent\TransactionalStorage.cs:line 222\r\n   at Raven.Database.DocumentDatabase..ctor(InMemoryRavenConfiguration configuration) in c:\Builds\raven\Raven.Database\DocumentDatabase.cs:line 181\r\n   at Raven.Database.Server.HttpServer.<>c__DisplayClass1d.<TryGetOrCreateResourceStore>b__1c(String s) in c:\Builds\raven\Raven.Database\Server\HttpServer.cs:line 652\r\n   at Raven.Abstractions.Extensions.ConcurrentDictionaryExtensions.GetOrAddAtomically[TKey,TVal](ConcurrentDictionary`2 self, TKey key, Func`2 valueFactory) in c:\Builds\raven\Raven.Abstractions\Extensions\ConcurrentDictionaryExtensions.cs:line 21\r\n   at Raven.Database.Server.HttpServer.TryGetOrCreateResourceStore(String tenantId, DocumentDatabase& database) in c:\Builds\raven\Raven.Database\Server\HttpServer.cs:line 622\r\n   at Raven.Database.Server.HttpServer.SetupRequestToProperDatabase(IHttpContext ctx) in c:\Builds\raven\Raven.Database\Server\HttpServer.cs:line 582\r\n   at Raven.Database.Server.HttpServer.DispatchRequest(IHttpContext ctx) in c:\Builds\raven\Raven.Database\Server\HttpServer.cs:line 501\r\n   at Raven.Database.Server.HttpServer.HandleActualRequest(IHttpContext ctx) in c:\Builds\raven\Raven.Database\Server\HttpServer.cs:line 303"
} ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.

**Comment by anton-iermolenko** [comment]
EsentLogDiskFullException: Log disk full

How much space have you allocated for Azure drive?

**Comment by rvwv** [comment]
20 giga,
i reinstall ravendb and the application in same datacenter,
and its solved,

thank you
